language: python
env:
- DATABASE_URL=postgresql://localhost/travis_ci_test
services:
- postgresql
branches:
  only: master
python:
- '3.6'
install:
- pip install -r requirements-travis.txt
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- python create_db.py
script:
- coverage run --source=app tests.py
after_success:
- coverage report
deploy:
  provider: heroku
  api_key:
    secure: SYpsXYfDkUE6vyyl6s6ouJGtj59ZTXD6LdrwyIii1DHtEdUW+gTueNAyvWWojnddRWhXF3VJ3BS1yBSPzMT7kDivWMju8Od366WHeL3K397zlQasTUzWs6icm2KPZfDcwEy2maXAQ3YkCUVBuxOPz/dM0TOsOfPlTTUns688OxmP8R6pfqzmd+R3iscSH39x4VaxK2sSq/fJwc7teR6msJksFo5XWOO+/tIMidO8IJjO5ilVqeRZN8k1fT4MrkCHR3xVvjk4/gDT5UIpC7YlUXdrK/3WLs/XHlLAHsKHdhKx5HYNfzJBFBszlHleBk65Rl4qzSYT9GBE5IzsOE4+N2Q/DJl9GILod7bcwpx9nG3b1A2i1/yiEMAMpWTdnbbPzIYqi4DFQLuHBzE9G/5V6ukLFEJ5d0RkJsFPVNW6S/3NLDHKtg64CSM8mw378wJ+zrlWPI2DXOFCt7K884pFb0CrDe6ESHzt0lqE/tydYvhDARutVlBxHfeK2oI9q37LQQGk1444/UrpUTSfvnWkiiXkJUBGhWm0HaPl80SlbG1ycd1v6oqJ/fbXXjMXmHvGweOf/kNHSnp+OXxFJUhwNAq9CSEodLMdivymfmU4tnvtG9uaVK/qQxzvGNnzU3MEM6XGtp8cJ/OdEBlwTNNf+1ZyBHSDKhTGcwj2MnArv70=
  app: dota-flask
  on:
    repo: wgx731/dota-flask
