language: python
env:
- DATABASE_URL=postgresql://localhost/travis_ci_test
services:
- postgresql
branches:
  only: master
python:
- '3.6'
install:
- pip install -r requirements-travis.txt
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- python create_db.py
script:
- coverage run --source=app tests.py
after_success:
- coverage report
deploy:
  provider: heroku
  api_key:
    secure: z6icEvzbHhAyom6b0z2z7rc4Q9x+b9Egs+Y0tuwN//An46n1P7Ab+IXB4r8oySMgi3jiTQlnuhCBpnKVPA3FfHmlO3CVQ4FlPnuypYqNVBgL8lpt847fH4cU9w+A5rLGwGtU3K01NKzsNADLbLCATyC9+gEv/mf6GxHF48oV5fNM/Zm0pG0f5CPQyXYnplb4Uf0RAhLD2Q+5JDvDJ9AEECMsgmXhPCl1S92EkMzxHhpC3qCQ4+rwJJpGcGZxlwNwq0oyWiMbYpmaVuSw6+17Lb3R1C2mi/zNHSaHsyDyQXnHRwyY/VvQLKDuNrjU2CoYMQ7AnISnzhoqrgHY6SFIe1ERDBou8qGMiSRcIhd9Z+/geJj8y7KLXX9HCZzBsQ/aJ83GnrNLKcMbGpHlGPQKDM/AyW72kWEZLJo9LSYxcwd23YkA3XW3BiBFyEfBUhmu/k015kQYX7ew8Bksz3g+e+wMLKzzpz84bZqO6M/KQLpReqjACXRJpspnhGyyftfqeA8zqKMV7Wxysr5TfadT45b0Ik9duCNjcaK63ghc7NQlYmdnaehUGGM9KQeSRVgqEB9FxzfMS5nk8ctgEsZucRmm73DWaUBC/5iLZzRtVdcHQC04D/ubAec+1y762pBoDzUnywthChZrtGjzqQxdedBVIdUIoRWP4n3IoprBWWY=
  app: dota-flask
  on:
    repo: wgx731/dota-flask
    branch: master