language: python
env:
- DATABASE_URL=postgresql://localhost/travis_ci_test
services:
- postgresql
python:
- '3.6'
install:
- pip install -r requirements-travis.txt
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- python create_db.py
script:
- coverage run --source=app tests.py
- sonar-scanner
after_success:
- coverage report
deploy:
  provider: heroku
  # token expire 2020-03-13
  api_key:
    secure: Has4f3vwA1YxMRoKzTyzMXHwofHR066h+pjQgJnnzadSsZ4bWT+V2SObaTh0SmQ1Wgf6WAUkRs8lFbz84N0nnhIAJr/uvy9fbuTlR00gS8RMLd5B3g2GWiNtekH8zS4srpQUkoM+FsDBO82xx3sYbOhF3eVSG691oXlxcfECAl6FBSWYAhheYkefPyIG6s8YAEVHhnYJ9xM2CYkwYDtPnytsTqkzWDWeag5lCfzLpfyzYpemNnxf5lnKCP4yCtNxc8gUZBiYOnt7phQ2K+MVfIRwBp30D6skim0kI3jAoPlPYsarriWTSNSmjwFAe2b38RckeS+T6bP8vrQO+UYNKNEG11n8NP2AvKb6rcIZx95V38tjg7QbapxfeHL/e6jRaxi+Jm/GxOQc1e0P9Ee2HGNAGsmGu28vB4sSzDB08MG++4veDISWxNhlwq2w+s4aoku/ChQrWsTFNtqGX0q0IG5A9BbRkR3QcDl4O1IxqVqaMTF2y7xRGnIa1eOrB868OqAQ4KsXuocjJ8r4qE7xwt9QSO3TMXECTqbU9mzDTXpZX2StKyqe8bhcF9ulpXhGpLYB3IsyvrfaEiJ4zmtQNCZ0kkqYZ9E0nZeA7Com+hBRYNN7rac9C+LDIaSyILf9KuowqasyWI6jc83YXu7lP03TWGUAs4l7e1huQmoToUI=
  app: dota-flask
  on: master
addons:
  sonarcloud:
    organization: wgx731-github
    token:
      secure: G+uYbGei6pOoY1UNZQp5K38tqv6ZgnISfXytWzEI+ylMkleDFp1vtfFrSz9ww5PGFr0gYM+qqDQvLjMYdZnuFahkKB169mxjSfPtpNyNOG7B1us3YW9MmqyH8FnXqgsBhCZpvmyPDPu039nrl4GJnJw+JkPRkhhSo7HQc3CAcRpVYmvRHIYMsGcydrquKQVOpscSf/iO3L3kiEHCvSMTx3L1nrPOKl1L8kQlBPPDSR0lSeXUJQ5BsURc2ClgRy+dC9lIEn07UUeZ4bYuoqaPs2AAlmhUA5rUn+t0+dbNrMbVLx5gYuYUPROFWWrPHzX5BC+KRFDuYMuEvvqNHHcSG77ENOrbxBauCWK40WpbTSi5TYkzuJLMn+U99t6ZzajS7RO1mMBhTjG0GiAXF2OGNn89nL835MM1Ui8MXB8tSnF9GZgj00dCG2Rx7vLotcdKE7kZLlSAw+Z+Ol5wwmEqYaXjDyCR75KISeGLI2l+rdsJ9R/W89YGgp3JD57ZRBPCpWL7s8cocbJd+S0bIsnaQf3fyymA8l1GKE+p0FMqP6rWZMZwn2GhWUP8DNYQlRYWHtZJcH5nHAl33wePUlCDRsh9pDGKvLpzXMB9lMRhAQV2aWpLCixLfj3b+aEt+duuVQlUYxYXUuv60lkqdSLehJm9l/feVP9f+FXghUXGqAs=
