language: python
env:
- DATABASE_URL=postgresql://localhost/travis_ci_test
services:
- postgresql
branches:
  only: master
python:
- '3.6'
install:
- pip install -r requirements-travis.txt
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- python create_db.py
script:
- coverage run --source=app tests.py
after_success:
- coverage report
deploy:
  provider: heroku
  app: dota-flask
  on:
    repo: wgx731/dota-flask
  api_key:
    secure: iuFzrkCfirlJ8rVoRMr4Nv8H/xkNBErd0o4TSkA1xB+4T34FIrjdJj4aAQYvLC10ogHdvstgRHlQMWqnBtDnrtcYq0iWKdwH0CXaK+tiNLAnZgdKtDO/H9LmgiWEiqHBvxTpfjMRAJT2rgbMV08iEyDdTGvLtNA8LKgvEpf9+iLKRmsNHBWUpqIUKAMIILxA7kKcAza5rP01bGy6TqpSk2Ty3zgMHGELdGUUlXllgJ7sv7DVcj+nK3HTQncHm+pMZwa+d4PN6vNLh3T9xnp/999/T6MbIWOZPcg4MyxB3MqkXOXCgEzizzDPumOSUbhdNA+OzLUyDaUmjXau7mxGcB1s8a3oaqLLr67vM0Aw6yzDSzJRhcOfl7jDo+XWBIPS35biUlcy6WpvXst7J6yz4YX9807WQZ4tGJR8Y7MaWToQ/GBGw1DDtR7R8ClFAbrZ1U401P/q5ZRQ6tgJp+bWCCibc9yjXT97oJntd2zBk1HptFpkluzSPK3Yolji9lOgM1jW0pQ2jmZGjpExqWi7bs1lgp6y3zIcASqnOZCYyfrJuY8dkAzD3z0EINnpJBFiTTnI3U8WaQ0Z4V/ueYJeQ2S/RIJuSyPTf1QXqeGAXUy9cAJwc4ZXZXIw5XKt3R5sB8eqCTcJP+6HkBuT/J/i7I3KqY4+tkqmNXzE1bs7avI=
