language: python
env:
- DATABASE_URL=postgresql://localhost/travis_ci_test
services:
- postgresql
python:
- '3.6'
install:
- pip install -r requirements-travis.txt
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- python create_db.py
script:
- coverage run --source=app tests.py
- sonar-scanner
after_success:
- coverage report
deploy:
  provider: heroku
  api_key:
    secure: c/e/VI27VIxkboeobj90HI5WyGKPcAuWYOwkkj0NWG1CDW4cD/rxQjQUPEQtnUWkC2KCdITQlJHis0RDouujYDmfbZM7Cgw166agwGmUQgR77I3zFGkJCE8UCkGwpuVxxYkjIGzzZy/mdRdWQTHUPczb+tM3MRdoJ8ju+M+J/ML+Hv4PX+7qpJ43QOUBu49jpKmYLl2DZv/xxGwgUKKLEPdNwQMJoIliW+uLw5sP+V9dV3oRejzGSa5yZg/ckKIO8Igr3nJNT8cvnCXxRBCJGJU64GGcsnxnRNi3tsMKU81GrMmQXhbHMfGAqutfX5J6r6UEF0kThA8abosZ5TpjtNeR9IGB1uUDZuNzNMD8T6IMtKqjEIgyog3RZeN0ZWrhiQ5S6TgfsVTmJQXN1r4KJ1usv3fTHtYBm97uyn3d/HT8E0SIqBI0AyHqw8u/i/PsxPOGr1npNSDhCr4fdknldmd6SO2AKaHYqGqETBytHepZg1VrvleSJV6n62k+IOQfsGkT8/HK1b58G0dKT46IQyz2PxQHfYba71OaP7F9wvMJe9LMoMBjARu42ldLmRtZCIdI64i7W6KMsxtbFyDMT7HKhcxYRUxikttktx4BxA7k665svXdVFYJEweA6h9DxQNB3zbnUqHUD8aazmt+YyQziSpelMa9vlAYPZnv8ErQ=
  app: dota-flask
  on: master
addons:
  sonarcloud:
    organization: wgx731-github
    token:
      secure: G+uYbGei6pOoY1UNZQp5K38tqv6ZgnISfXytWzEI+ylMkleDFp1vtfFrSz9ww5PGFr0gYM+qqDQvLjMYdZnuFahkKB169mxjSfPtpNyNOG7B1us3YW9MmqyH8FnXqgsBhCZpvmyPDPu039nrl4GJnJw+JkPRkhhSo7HQc3CAcRpVYmvRHIYMsGcydrquKQVOpscSf/iO3L3kiEHCvSMTx3L1nrPOKl1L8kQlBPPDSR0lSeXUJQ5BsURc2ClgRy+dC9lIEn07UUeZ4bYuoqaPs2AAlmhUA5rUn+t0+dbNrMbVLx5gYuYUPROFWWrPHzX5BC+KRFDuYMuEvvqNHHcSG77ENOrbxBauCWK40WpbTSi5TYkzuJLMn+U99t6ZzajS7RO1mMBhTjG0GiAXF2OGNn89nL835MM1Ui8MXB8tSnF9GZgj00dCG2Rx7vLotcdKE7kZLlSAw+Z+Ol5wwmEqYaXjDyCR75KISeGLI2l+rdsJ9R/W89YGgp3JD57ZRBPCpWL7s8cocbJd+S0bIsnaQf3fyymA8l1GKE+p0FMqP6rWZMZwn2GhWUP8DNYQlRYWHtZJcH5nHAl33wePUlCDRsh9pDGKvLpzXMB9lMRhAQV2aWpLCixLfj3b+aEt+duuVQlUYxYXUuv60lkqdSLehJm9l/feVP9f+FXghUXGqAs=
